<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />

	<PropertyGroup>
		<PackageId>HuanskyFW.EventBus</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\HuanskyFW.Core\HuanskyFW.Core.csproj" />
		<ProjectReference Include="..\HuanskyFW.EventBus.Abstractions\HuanskyFW.EventBus.Abstractions.csproj" />
	</ItemGroup>

</Project>
