<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.props" />

	<PropertyGroup>
		<PackageId>HuanskyFW.RemoteServices.Grpc</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.54.0" />
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.54.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HuanskyFW.RemoteServices\HuanskyFW.RemoteServices.csproj" />
	</ItemGroup>

</Project>
