<Project>

	<PropertyGroup>
		<!--dotnet配置-->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<!--项目信息-->
		<Version>1.0.0</Version>
		<Authors>shl</Authors>
		<Company>Huansky Co.,Ltd.</Company>
		<Copyright>© 2023-present Huansky Co.,Ltd.</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>NuGet.md</PackageReadmeFile>
		<PackageIcon>logo.png</PackageIcon>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<!--<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>logo.png</PackageIcon>-->
		<PackageOutputPath>$(SolutionDir)\.nupkgs</PackageOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<RootNamespace />
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
	</PropertyGroup>

	<ItemGroup>
		<None Include="NuGet.md" Pack="true" PackagePath="\"/>
		<None Include="logo.png" Pack="true" PackagePath="\"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>