<Project>

	<PropertyGroup>
		<!--dotnet配置-->
		<LangVersion>latest</LangVersion>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<NoWarn>$(NoWarn);CS1591;CS0436</NoWarn>
	</PropertyGroup>

	<PropertyGroup>
		<IsTestProject Condition="$(MSBuildProjectFullPath.Contains('Tests')) and ($(MSBuildProjectName.EndsWith('.Tests')) or $(MSBuildProjectName.EndsWith('.Test.Base')))">true</IsTestProject>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<!-- 测试项目不打包 -->
		<IsPackable>false</IsPackable>
		<!-- 测试项目不生成文档 -->
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsTestProject)' == 'true'">
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="NUnit.Analyzers" />
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>