<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<PackageId>HuanskyFW.Serialize.Json.Abstractions</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Core\HuanskyFW.Core\HuanskyFW.Core.csproj" />
	</ItemGroup>

</Project>
